# Generated by Django 4.1.2 on 2022-12-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
