# Generated by Django 4.1.2 on 2022-12-15 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_price_auctionlisting_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='add_to_watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
