# Generated by Django 4.1.2 on 2022-12-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_add_to_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='add_to_watchlist',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='add_to_watchlist',
            field=models.BooleanField(default=True),
        ),
    ]
