# Generated by Django 4.1.2 on 2022-12-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auctionlisting_add_to_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='add_to_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
