# Generated by Django 4.1.2 on 2022-12-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlisting_add_to_watchlist_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
