# Generated by Django 4.1.2 on 2022-12-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctionlisting_isactive_delete_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
